export type EmojiItem = {
  emoji: string;
  keywords: string[];
};

export const ALL_EMOJIS: EmojiItem[] = [
  // Travel & Places
  { emoji: '🧭', keywords: ['compass', 'navigation', 'direction', 'north', 'east', 'south', 'west'] },
  { emoji: '📍', keywords: ['pin', 'location', 'map', 'place', 'here'] },
  { emoji: '🚩', keywords: ['flag', 'red', 'mark', 'sign'] },
  { emoji: '🏁', keywords: ['flag', 'checkered', 'finish', 'race', 'start'] },
  { emoji: '🗺️', keywords: ['map', 'world', 'travel'] },
  { emoji: '🏔️', keywords: ['mountain', 'snow', 'peak', 'everest', 'alps'] },
  { emoji: '⛰️', keywords: ['mountain', 'hill', 'nature'] },
  { emoji: '🌋', keywords: ['volcano', 'eruption', 'lava'] },
  { emoji: '🗻', keywords: ['mount fuji', 'mountain', 'japan'] },
  { emoji: '🏕️', keywords: ['camping', 'tent', 'outdoors'] },
  { emoji: '⛺', keywords: ['tent', 'camping'] },
  { emoji: '🏠', keywords: ['house', 'home', 'building'] },
  { emoji: '🏡', keywords: ['house', 'garden', 'home'] },
  { emoji: '🏢', keywords: ['office', 'building', 'work'] },
  { emoji: '🏣', keywords: ['post office', 'building'] },
  { emoji: '🏤', keywords: ['post office', 'european'] },
  { emoji: '🏥', keywords: ['hospital', 'doctor', 'medical'] },
  { emoji: '🏦', keywords: ['bank', 'money', 'building'] },
  { emoji: '🏨', keywords: ['hotel', 'accommodation', 'sleep'] },
  { emoji: '🏪', keywords: ['convenience store', 'shop', '24/7'] },
  { emoji: '🏫', keywords: ['school', 'education', 'building'] },
  { emoji: '🏭', keywords: ['factory', 'industry', 'building'] },
  { emoji: '🏰', keywords: ['castle', 'fortress', 'history'] },
  { emoji: '🗼', keywords: ['tokyo tower', 'tower'] },
  { emoji: '🗽', keywords: ['statue of liberty', 'new york', 'usa'] },
  { emoji: '⛪', keywords: ['church', 'religion', 'building'] },
  { emoji: '🕌', keywords: ['mosque', 'religion', 'islam'] },
  { emoji: '🛕', keywords: ['hindu temple', 'religion'] },
  { emoji: '🕍', keywords: ['synagogue', 'religion', 'jewish'] },
  { emoji: '⛩️', keywords: ['shinto shrine', 'religion', 'japan'] },
  { emoji: '⛲', keywords: ['fountain', 'water', 'park'] },
  { emoji: '🏙️', keywords: ['city', 'skyline', 'buildings'] },
  { emoji: '🌆', keywords: ['city', 'sunset', 'evening'] },
  { emoji: '🌃', keywords: ['city', 'night', 'stars'] },
  { emoji: '🌉', keywords: ['bridge', 'night', 'san francisco'] },
  { emoji: '🎠', keywords: ['carousel', 'horse', 'amusement park'] },
  { emoji: '🎡', keywords: ['ferris wheel', 'amusement park'] },
  { emoji: '🎢', keywords: ['roller coaster', 'amusement park'] },
  { emoji: '🚂', keywords: ['locomotive', 'train', 'steam'] },
  { emoji: '🚃', keywords: ['railway car', 'train', 'electric'] },
  { emoji: '🚄', keywords: ['shinkansen', 'train', 'speed'] },
  { emoji: '🚅', keywords: ['bullet train', 'speed'] },
  { emoji: '🚆', keywords: ['train', 'transport'] },
  { emoji: '🚇', keywords: ['metro', 'subway', 'underground'] },
  { emoji: '🚈', keywords: ['light rail', 'train'] },
  { emoji: '🚉', keywords: ['station', 'train'] },
  { emoji: '🚊', keywords: ['tram', 'trolley'] },
  { emoji: '🚝', keywords: ['monorail', 'train'] },
  { emoji: '🚞', keywords: ['mountain railway', 'train'] },
  { emoji: '🚋', keywords: ['tram', 'car'] },
  { emoji: '🚌', keywords: ['bus', 'transport'] },
  { emoji: '🚍', keywords: ['bus', 'oncoming'] },
  { emoji: '🚎', keywords: ['trolleybus', 'bus'] },
  { emoji: '🚐', keywords: ['minibus', 'van'] },
  { emoji: '🚑', keywords: ['ambulance', 'medical', 'emergency'] },
  { emoji: '🚒', keywords: ['fire engine', 'truck', 'emergency'] },
  { emoji: '🚓', keywords: ['police car', 'cop'] },
  { emoji: '🚔', keywords: ['police car', 'oncoming'] },
  { emoji: '🚕', keywords: ['taxi', 'cab'] },
  { emoji: '🚖', keywords: ['taxi', 'oncoming'] },
  { emoji: '🚗', keywords: ['car', 'automobile'] },
  { emoji: '🚘', keywords: ['car', 'oncoming'] },
  { emoji: '🚙', keywords: ['suv', 'car', 'recreational'] },
  { emoji: '🚚', keywords: ['truck', 'delivery'] },
  { emoji: '🚛', keywords: ['articulated lorry', 'truck'] },
  { emoji: '🚜', keywords: ['tractor', 'farm'] },
  { emoji: '🏎️', keywords: ['racing car', 'f1', 'speed'] },
  { emoji: '🏍️', keywords: ['motorcycle', 'bike'] },
  { emoji: '🛵', keywords: ['scooter', 'motor'] },
  { emoji: '🦽', keywords: ['wheelchair', 'manual'] },
  { emoji: '🦼', keywords: ['wheelchair', 'motorized'] },
  { emoji: '🚲', keywords: ['bicycle', 'bike', 'cycling'] },
  { emoji: '🛴', keywords: ['kick scooter', 'scooter'] },
  { emoji: '🛹', keywords: ['skateboard', 'board'] },
  { emoji: '🚏', keywords: ['bus stop', 'sign'] },
  { emoji: '🛣️', keywords: ['motorway', 'road', 'highway'] },
  { emoji: '🛤️', keywords: ['railway track', 'train'] },
  { emoji: '🛢️', keywords: ['oil drum', 'fuel'] },
  { emoji: '⛽', keywords: ['fuel pump', 'gas', 'petrol'] },
  { emoji: '🚨', keywords: ['police car light', 'emergency', 'siren'] },
  { emoji: '🚥', keywords: ['traffic light', 'horizontal'] },
  { emoji: '🚦', keywords: ['traffic light', 'vertical'] },
  { emoji: '🛑', keywords: ['stop sign', 'red'] },
  { emoji: '🚧', keywords: ['construction', 'barrier'] },
  { emoji: '⚓', keywords: ['anchor', 'ship', 'sea'] },
  { emoji: '⛵', keywords: ['sailboat', 'boat', 'sea'] },
  { emoji: '🛶', keywords: ['canoe', 'boat'] },
  { emoji: '🚤', keywords: ['speedboat', 'boat'] },
  { emoji: '🛳️', keywords: ['passenger ship', 'cruise'] },
  { emoji: '⛴️', keywords: ['ferry', 'boat'] },
  { emoji: '🛥️', keywords: ['motor boat', 'boat'] },
  { emoji: '🚢', keywords: ['ship', 'boat'] },
  { emoji: '✈️', keywords: ['airplane', 'flight', 'fly'] },
  { emoji: '🛩️', keywords: ['small airplane', 'flight'] },
  { emoji: '🛫', keywords: ['airplane departure', 'takeoff'] },
  { emoji: '🛬', keywords: ['airplane arrival', 'landing'] },
  { emoji: '🪂', keywords: ['parachute', 'skydiving'] },
  { emoji: '💺', keywords: ['seat', 'chair'] },
  { emoji: '🚁', keywords: ['helicopter', 'fly'] },
  { emoji: '🚟', keywords: ['suspension railway', 'train'] },
  { emoji: '🚠', keywords: ['mountain cableway', 'cable car'] },
  { emoji: '🚡', keywords: ['aerial tramway', 'cable car'] },
  { emoji: '🛰️', keywords: ['satellite', 'space'] },
  { emoji: '🚀', keywords: ['rocket', 'space', 'launch'] },
  { emoji: '🛸', keywords: ['flying saucer', 'ufo', 'alien'] },

  // Nature
  { emoji: '🌲', keywords: ['evergreen tree', 'nature', 'forest'] },
  { emoji: '🌳', keywords: ['deciduous tree', 'nature', 'forest'] },
  { emoji: '🌴', keywords: ['palm tree', 'beach', 'tropical'] },
  { emoji: '🌵', keywords: ['cactus', 'desert'] },
  { emoji: '🌾', keywords: ['sheaf of rice', 'grain', 'farm'] },
  { emoji: '🌿', keywords: ['herb', 'plant', 'nature'] },
  { emoji: '☘️', keywords: ['shamrock', 'plant', 'luck'] },
  { emoji: '🍀', keywords: ['four leaf clover', 'luck'] },
  { emoji: '🍁', keywords: ['maple leaf', 'autumn', 'canada'] },
  { emoji: '🍂', keywords: ['fallen leaf', 'autumn'] },
  { emoji: '🍃', keywords: ['leaf fluttering in wind', 'wind'] },
  { emoji: '🍄', keywords: ['mushroom', 'fungus'] },
  { emoji: '🌰', keywords: ['chestnut', 'nut'] },
  { emoji: '🦀', keywords: ['crab', 'sea', 'food'] },
  { emoji: '🦞', keywords: ['lobster', 'sea', 'food'] },
  { emoji: '🦐', keywords: ['shrimp', 'sea', 'food'] },
  { emoji: '🦑', keywords: ['squid', 'sea', 'food'] },
  { emoji: '🌍', keywords: ['globe europe-africa', 'earth', 'world'] },
  { emoji: '🌎', keywords: ['globe americas', 'earth', 'world'] },
  { emoji: '🌏', keywords: ['globe asia-australia', 'earth', 'world'] },
  { emoji: '🌑', keywords: ['new moon', 'moon', 'space'] },
  { emoji: '🌒', keywords: ['waxing crescent moon', 'moon'] },
  { emoji: '🌓', keywords: ['first quarter moon', 'moon'] },
  { emoji: '🌔', keywords: ['waxing gibbous moon', 'moon'] },
  { emoji: '🌕', keywords: ['full moon', 'moon'] },
  { emoji: '🌖', keywords: ['waning gibbous moon', 'moon'] },
  { emoji: '🌗', keywords: ['last quarter moon', 'moon'] },
  { emoji: '🌘', keywords: ['waning crescent moon', 'moon'] },
  { emoji: '🌙', keywords: ['crescent moon', 'night'] },
  { emoji: '🌚', keywords: ['new moon face', 'moon'] },
  { emoji: '🌛', keywords: ['first quarter moon face', 'moon'] },
  { emoji: '🌜', keywords: ['last quarter moon face', 'moon'] },
  { emoji: '☀️', keywords: ['sun', 'weather', 'day'] },
  { emoji: '🌝', keywords: ['full moon face', 'moon'] },
  { emoji: '🌞', keywords: ['sun with face', 'sun'] },
  { emoji: '⭐', keywords: ['star', 'night'] },
  { emoji: '🌟', keywords: ['glowing star', 'star'] },
  { emoji: '🌠', keywords: ['shooting star', 'wish'] },
  { emoji: '☁️', keywords: ['cloud', 'weather'] },
  { emoji: '⛅', keywords: ['sun behind cloud', 'weather'] },
  { emoji: '⛈️', keywords: ['cloud with lightning and rain', 'storm'] },
  { emoji: '🌤️', keywords: ['sun behind small cloud', 'weather'] },
  { emoji: '🌥️', keywords: ['sun behind large cloud', 'weather'] },
  { emoji: '🌦️', keywords: ['sun behind rain cloud', 'weather'] },
  { emoji: '🌧️', keywords: ['cloud with rain', 'rain'] },
  { emoji: '🌨️', keywords: ['cloud with snow', 'snow'] },
  { emoji: '🌩️', keywords: ['cloud with lightning', 'storm'] },
  { emoji: '🌪️', keywords: ['tornado', 'storm'] },
  { emoji: '🌫️', keywords: ['fog', 'weather'] },
  { emoji: '🌬️', keywords: ['wind face', 'wind'] },
  { emoji: '🌀', keywords: ['cyclone', 'storm'] },
  { emoji: '🌈', keywords: ['rainbow', 'weather'] },
  { emoji: '🌂', keywords: ['closed umbrella', 'rain'] },
  { emoji: '☂️', keywords: ['umbrella', 'rain'] },
  { emoji: '☔', keywords: ['umbrella with rain drops', 'rain'] },
  { emoji: '⛱️', keywords: ['umbrella on ground', 'beach'] },
  { emoji: '⚡', keywords: ['high voltage', 'lightning', 'power'] },
  { emoji: '❄️', keywords: ['snowflake', 'snow', 'winter'] },
  { emoji: '☃️', keywords: ['snowman', 'snow', 'winter'] },
  { emoji: '⛄', keywords: ['snowman without snow', 'snow'] },
  { emoji: '🔥', keywords: ['fire', 'hot', 'burn'] },
  { emoji: '💧', keywords: ['droplet', 'water'] },
  { emoji: '🌊', keywords: ['water wave', 'sea', 'ocean'] },

  // Activities
  { emoji: '🚶', keywords: ['person walking', 'hike'] },
  { emoji: '🏃', keywords: ['person running', 'run'] },
  { emoji: '💃', keywords: ['woman dancing', 'dance'] },
  { emoji: '🕺', keywords: ['man dancing', 'dance'] },
  { emoji: '👯', keywords: ['people with bunny ears', 'party'] },
  { emoji: '🧖', keywords: ['person in steamy room', 'sauna'] },
  { emoji: '🧗', keywords: ['person climbing', 'rock climbing'] },
  { emoji: '🧘', keywords: ['person in lotus position', 'yoga'] },
  { emoji: '🛀', keywords: ['person taking bath', 'bath'] },
  { emoji: '🛌', keywords: ['person in bed', 'sleep'] },
  { emoji: '🏇', keywords: ['horse racing', 'horse'] },
  { emoji: '🏂', keywords: ['snowboarder', 'snow'] },
  { emoji: '🏊', keywords: ['person swimming', 'swim'] },
  { emoji: '🏄', keywords: ['person surfing', 'surf'] },
  { emoji: '🚣', keywords: ['person rowing boat', 'row'] },
  { emoji: '🤽', keywords: ['person playing water polo', 'water'] },
  { emoji: '🤾', keywords: ['person playing handball', 'handball'] },
  { emoji: '⛹️', keywords: ['person bouncing ball', 'basketball'] },
  { emoji: '🏋️', keywords: ['person lifting weights', 'gym'] },
  { emoji: '🚴', keywords: ['person biking', 'bike'] },
  { emoji: '🚵', keywords: ['person mountain biking', 'bike'] },
  { emoji: '🤸', keywords: ['person cartwheeling', 'gymnastics'] },
  { emoji: '🤼', keywords: ['people wrestling', 'wrestle'] },
  { emoji: '🤽', keywords: ['person playing water polo', 'water'] },
  { emoji: '🤾', keywords: ['person playing handball', 'handball'] },
  { emoji: '🤹', keywords: ['person juggling', 'juggle'] },

  // Objects & Symbols
  { emoji: '⌚', keywords: ['watch', 'time'] },
  { emoji: '📱', keywords: ['mobile phone', 'cell'] },
  { emoji: '📲', keywords: ['mobile phone with arrow', 'call'] },
  { emoji: '💻', keywords: ['laptop', 'computer'] },
  { emoji: '⌨️', keywords: ['keyboard', 'computer'] },
  { emoji: '🖥️', keywords: ['desktop computer', 'computer'] },
  { emoji: '🖨️', keywords: ['printer', 'print'] },
  { emoji: '🖱️', keywords: ['computer mouse', 'click'] },
  { emoji: '🖲️', keywords: ['trackball', 'computer'] },
  { emoji: '🕹️', keywords: ['joystick', 'game'] },
  { emoji: '🗜️', keywords: ['clamp', 'tool'] },
  { emoji: '💽', keywords: ['computer disk', 'save'] },
  { emoji: '💾', keywords: ['floppy disk', 'save'] },
  { emoji: '💿', keywords: ['optical disk', 'cd'] },
  { emoji: '📀', keywords: ['dvd', 'disk'] },
  { emoji: '📼', keywords: ['videocassette', 'vhs'] },
  { emoji: '📷', keywords: ['camera', 'photo'] },
  { emoji: '📸', keywords: ['camera with flash', 'photo'] },
  { emoji: '📹', keywords: ['video camera', 'movie'] },
  { emoji: '🎥', keywords: ['movie camera', 'film'] },
  { emoji: '📽️', keywords: ['film projector', 'movie'] },
  { emoji: '🎞️', keywords: ['film frames', 'movie'] },
  { emoji: '📞', keywords: ['telephone receiver', 'call'] },
  { emoji: '☎️', keywords: ['telephone', 'call'] },
  { emoji: '📟', keywords: ['pager', 'beep'] },
  { emoji: '📠', keywords: ['fax machine', 'fax'] },
  { emoji: '📺', keywords: ['television', 'tv'] },
  { emoji: '📻', keywords: ['radio', 'music'] },
  { emoji: '🎙️', keywords: ['studio microphone', 'music'] },
  { emoji: '🎚️', keywords: ['level slider', 'music'] },
  { emoji: '🎛️', keywords: ['control knobs', 'music'] },
  { emoji: '⏱️', keywords: ['stopwatch', 'time'] },
  { emoji: '⏲️', keywords: ['timer clock', 'time'] },
  { emoji: '⏰', keywords: ['alarm clock', 'time'] },
  { emoji: '🕰️', keywords: ['mantelpiece clock', 'time'] },
  { emoji: '⌛', keywords: ['hourglass done', 'time'] },
  { emoji: '⏳', keywords: ['hourglass not done', 'time'] },
  { emoji: '📡', keywords: ['satellite antenna', 'dish'] },
  { emoji: '🔋', keywords: ['battery', 'power'] },
  { emoji: '🔌', keywords: ['electric plug', 'power'] },
  { emoji: '💡', keywords: ['light bulb', 'idea'] },
  { emoji: '🔦', keywords: ['flashlight', 'light'] },
  { emoji: '🕯️', keywords: ['candle', 'light'] },
  { emoji: '🗑️', keywords: ['wastebasket', 'trash'] },
  { emoji: '🛢️', keywords: ['oil drum', 'oil'] },
  { emoji: '💸', keywords: ['money with wings', 'cash'] },
  { emoji: '💵', keywords: ['dollar banknote', 'money'] },
  { emoji: '💴', keywords: ['yen banknote', 'money'] },
  { emoji: '💶', keywords: ['euro banknote', 'money'] },
  { emoji: '💷', keywords: ['pound banknote', 'money'] },
  { emoji: '💰', keywords: ['money bag', 'cash'] },
  { emoji: '💳', keywords: ['credit card', 'money'] },
  { emoji: '💎', keywords: ['gem stone', 'diamond'] },
  { emoji: '⚖️', keywords: ['balance scale', 'justice'] },
  { emoji: '🔧', keywords: ['wrench', 'tool'] },
  { emoji: '🔨', keywords: ['hammer', 'tool'] },
  { emoji: '⚒️', keywords: ['hammer and pick', 'tool'] },
  { emoji: '🛠️', keywords: ['hammer and wrench', 'tool'] },
  { emoji: '⛏️', keywords: ['pick', 'tool'] },
  { emoji: '🔩', keywords: ['nut and bolt', 'tool'] },
  { emoji: '⚙️', keywords: ['gear', 'settings'] },
  { emoji: '⛓️', keywords: ['chains', 'metal'] },
  { emoji: '🔫', keywords: ['pistol', 'gun'] },
  { emoji: '💣', keywords: ['bomb', 'boom'] },
  { emoji: '🔪', keywords: ['kitchen knife', 'cut'] },
  { emoji: '🗡️', keywords: ['dagger', 'knife'] },
  { emoji: '⚔️', keywords: ['crossed swords', 'fight'] },
  { emoji: '🛡️', keywords: ['shield', 'protect'] },
  { emoji: '🚬', keywords: ['cigarette', 'smoke'] },
  { emoji: '⚰️', keywords: ['coffin', 'death'] },
  { emoji: '⚱️', keywords: ['funeral urn', 'death'] },
  { emoji: '🏺', keywords: ['amphora', 'vase'] },
  { emoji: '🔮', keywords: ['crystal ball', 'magic'] },
  { emoji: '📿', keywords: ['prayer beads', 'religion'] },
  { emoji: '🧿', keywords: ['nazar amulet', 'charm'] },
  { emoji: '💈', keywords: ['barber pole', 'hair'] },
  { emoji: '⚗️', keywords: ['alembic', 'chemistry'] },
  { emoji: '🔭', keywords: ['telescope', 'space'] },
  { emoji: '🔬', keywords: ['microscope', 'science'] },
  { emoji: '🕳️', keywords: ['hole', 'dark'] },
  { emoji: '💊', keywords: ['pill', 'medicine'] },
  { emoji: '💉', keywords: ['syringe', 'doctor'] },
  { emoji: '🩸', keywords: ['drop of blood', 'medical'] },
  { emoji: '🧬', keywords: ['dna', 'science'] },
  { emoji: '🩹', keywords: ['adhesive bandage', 'medical'] },
  { emoji: '🩺', keywords: ['stethoscope', 'doctor'] },
  { emoji: '🌡️', keywords: ['thermometer', 'temperature'] },
  { emoji: '🏷️', keywords: ['label', 'tag'] },
  { emoji: '🔖', keywords: ['bookmark', 'mark'] },
  { emoji: '🚽', keywords: ['toilet', 'bathroom'] },
  { emoji: '🚿', keywords: ['shower', 'bathroom'] },
  { emoji: '🛁', keywords: ['bathtub', 'bathroom'] },
  { emoji: '🛀', keywords: ['person taking bath', 'bath'] },
  { emoji: '🧼', keywords: ['soap', 'clean'] },
  { emoji: '🧽', keywords: ['sponge', 'clean'] },
  { emoji: '🧹', keywords: ['broom', 'clean'] },
  { emoji: '🧺', keywords: ['basket', 'laundry'] },
  { emoji: '🧻', keywords: ['roll of paper', 'toilet'] },
  { emoji: '🔑', keywords: ['key', 'lock'] },
  { emoji: '🗝️', keywords: ['old key', 'lock'] },
  { emoji: '🛋️', keywords: ['couch and lamp', 'furniture'] },
  { emoji: '🛏️', keywords: ['bed', 'sleep'] },
  { emoji: '🛌', keywords: ['person in bed', 'sleep'] },
  { emoji: '🚪', keywords: ['door', 'enter'] },
  { emoji: '🧳', keywords: ['luggage', 'travel'] },
  { emoji: '🛎️', keywords: ['bellhop bell', 'hotel'] },
  { emoji: '🖼️', keywords: ['framed picture', 'art'] },
  { emoji: '🧭', keywords: ['compass', 'navigation'] },
  { emoji: '🧱', keywords: ['brick', 'wall'] },
  { emoji: '🧯', keywords: ['fire extinguisher', 'fire'] },
  { emoji: '🛒', keywords: ['shopping cart', 'shop'] },
];
